# Generated by Django 4.2.23 on 2025-07-08 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Solana Wallet Adresse (z.B. Base58-kodierter Public Key)",
                        max_length=44,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Ein optionaler, benutzerdefinierter Name für das Wallet",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Zeitpunkt, zu dem das Wallet hinzugefügt wurde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        help_text="Eindeutige Transaktionssignatur (Base58-kodiert)",
                        max_length=88,
                        unique=True,
                    ),
                ),
                (
                    "block_time",
                    models.BigIntegerField(
                        help_text="Unix-Timestamp der Transaktion (Zeitpunkt, zu dem sie in einen Block aufgenommen wurde)"
                    ),
                ),
                (
                    "slot",
                    models.BigIntegerField(
                        help_text="Der Slot, in dem die Transaktion bestätigt wurde"
                    ),
                ),
                (
                    "fee",
                    models.BigIntegerField(help_text="Transaktionsgebühr in Lamports"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Eine kurze Beschreibung oder Notiz zur Transaktion",
                        null=True,
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Zeitpunkt, zu dem die Transaktion in die Datenbank importiert wurde",
                    ),
                ),
                (
                    "meta_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zusätzliche Metadaten aus der RPC-Antwort (z.B. meta.preBalances, postBalances, etc.)",
                        null=True,
                    ),
                ),
                (
                    "raw_transaction_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Die vollständige rohe Transaktion von get_transaction",
                        null=True,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Das Wallet, zu dem diese Transaktion gehört",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet_manager.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaktion",
                "verbose_name_plural": "Transaktionen",
                "ordering": ["-block_time"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-block_time"],
                        name="wallet_mana_wallet__df30ef_idx",
                    ),
                    models.Index(
                        fields=["signature"], name="wallet_mana_signatu_a761fe_idx"
                    ),
                ],
            },
        ),
    ]
